version: '2'
services:
  rabbit:
    image: rabbitmq:3.6-alpine
    container_name: rabbit
    ports:
      - "5672:5672"

  worker:
    build: .
    container_name: worker
    command: celery -A products.main worker -l info --beat
    volumes:
      - .:/worker
      - ./logs:/inventory
    depends_on:
      - rabbit
    environment:
      - INVENTORY_PATH=/inventory
